= The Hello Ruby World

Yesterday a friend of mine, https://twitter.com/tilljoel[@tilljoel], asked me about how to get started with http://neo4j.org[Neo4j] in ruby - so here is a small step-by-step guide to get the usual "Hello World" going.

Firstly, I like to use Cypher as a query language and want to install the Neoj4 server as standard as possible on my OSX, via brew, and open the web interface in the browser for comfort:

[source, bash]
----
brew install neo4j && neo4j start
open http://localhost:7474/
----

Secondly, just make a new directory for the project with a file `hello.rb` for our script. We are going to use https://twitter.com/maxdemarzi[Max DeMarzi]'s nice https://github.com/maxdemarzi/neography[Neography] library, currently probably the best maintained Neo4j driver for Ruby.

[source,bash]
----
git clone https://github.com/peterneubauer/blogs.git
cd blogs/hello_world_ruby
bundle install
----

I am only using http://docs.neo4j.org/refcard/2.0/[Cypher] to interact with neo4j through the https://github.com/maxdemarzi/neography/wiki/Transactions#start-of-content[transactional REST endpoint], so the interface becomes very uniform in parsing the underlying HTTP responses - basically arrays of data coming back from Neo4j.
Now, `hello.rb` looks something like this:

[source, ruby]
----
require 'rubygems'
require 'neography'

#set up the Neo4j connection default client
@neo = Neography::Rest.new

#insert some data
@neo.commit_transaction("create  ({name:'Hello'})-[:CRUEL]->({name:'World'})")

#retrieve some data
@neo.commit_transaction("match (s)-[r]->(e) return s.name as start, type(r), e.name as end")['results'][0]['data'][0]['row'].each do |value|
	puts "Got column: #{value}"
end
----

Executing the file with

[source, bash]
----
ruby hello.rb
----

Results in an output of

[source]
----
Got column: Hello
Got column: CRUEL
Got column: World
----


Here you go, Joel! The code for this blog is available https://github.com/peterneubauer/blogs/blob/master/hello_world_ruby/[here at Github].
If you can make it even easier, please give me a pull request and I promise to merge it :)

/peter



